### ISSUE TITLE
Missing Iris 1.1.5 installation package macOS

### ISSUE THREAD

**Issue by warmitu** [danielng01/product-builds#5]
Hi,

I have a license for Iris version 1.1.5. The product updated automatically to version 1.2.0 which does not accept my activation code. If I try to download the specific 1.1.5 version from macOS I cannot find the build on Github. 
<img width="574" alt="image" src="https://user-images.githubusercontent.com/4567759/185110886-e7aff1c4-7efe-4f88-8654-b185c00895b2.png">

Note: this is a company bulk license purchase affecting ~150 people. 

Thanks,
Horia Pop

**Comment by danielng01** [comment]
hello, please write to us in Discord
on Windows there is version 1.1.5 

we will provide additional licenses for the affected devices
https://discord.gg/j4PgP7F
